// src/pages/vue-demo/_App.vue
<script setup lang="ts">
import { ref } from "vue";

const count = ref<number>(0);
</script>

<template>
  <div>
    <div class="space-y-4">
      <h2 class="text-xl font-semibold">カウンター</h2>
      <div class="text-center text-xl">{{ count }}</div>
      <div class="grid gap-4 grid-cols-3">
        <button @click="count--" class="block p-4 border">-1</button>
        <button @click="count = 0" class="block p-4 border">0</button>
        <button @click="count++" class="block p-4 border">+1</button>
      </div>
    </div>
  </div>
</template>

// src/pages/react-demo/_App.tsx
import { useState } from "react";

const App = () => {
  const [count, setCount] = useState<number>(0);

  return (
    <div>
      <div className="space-y-4">
        <h2 className="text-xl font-semibold">カウンター</h2>
        <div className="text-center text-xl">{count}</div>
        <div className="grid gap-4 grid-cols-3">
          <button
            onClick={() => {
              setCount((c) => c - 1);
            }}
            className="block p-4 border"
          >
            -1
          </button>
          <button onClick={() => setCount(0)} className="block p-4 border">
            0
          </button>
          <button
            onClick={() => setCount((c) => c + 1)}
            className="block p-4 border"
          >
            +1
          </button>
        </div>
      </div>
    </div>
  );
};

export default App;
